trigger:
- main

pool:
  name: Projeto

stages:
- stage: Dev
  displayName: Dev
  jobs:
  - job: CI
    displayName: CI
    steps:
    - task: CmdLine@2
      displayName: Clone Repository
      inputs:
        script: 'git clone https://github.com/EdnaldoLourenco/DevOps-CI-CD-Projeto.git'
        
    - task: SonarQubePrepare@7
      inputs:
        SonarQube: 'svc-sonar'
        scannerMode: 'cli'
        configMode: 'manual'
        cliProjectKey: 'myproject'
        cliProjectName: 'CI/CD'
        cliSources: '.'
        extraProperties: 

    - task: SonarQubeAnalyze@7
      displayName: SonarAnalyze
      inputs:
        jdkversion: 'JAVA_HOME'
    
    - task: SonarQubePublish@7
      displayName: SonarGate
      inputs:
        pollingTimeoutSec: '300'
    
