trigger:
- main

variables:
  system.debug: true
  imageRepository: 'devops-ci-cd'
  tag: '$(Build.BuildId)'

pool:
  vmImage: ubuntu-latest

stages:
- stage: Dev
  displayName: Dev
  jobs:
  - job: CI
    displayName: CI
    steps:
    - checkout: self
      fetchDepth: 0
    
    - task: SonarCloudPrepare@3
      inputs:
        SonarQube: 'svc-sonarcloud'
        organization: 'juniorramos0015'
        scannerMode: 'cli'
        configMode: 'manual'
        cliProjectKey: 'juniorramos0015_DevOps-CI-CD-Amazon-Prime-Clone-Project'
        cliProjectName: 'DevOps CI-CD Amazon Prime Clone Project'
        cliSources: '.'
    - task: SonarCloudAnalyze@3
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'
    - task: SonarCloudPublish@3
      inputs:
        pollingTimeoutSec: '300'

    
    - task: Docker@2
      displayName: Docker Login
      inputs:
        containerRegistry: 'svc-acr'
        command: 'login'

    - task: Docker@2
      displayName: Build the Image
      inputs:
        containerRegistry: 'svc-acr'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: './Dockerfile'
        tags: '$(tag)'
    
    - task: trivy@1
      inputs:
        version: 'latest'
        debug: true
        loginDockerConfig: true
        image: 'acrprojeto.azurecr.io/devops-ci-cd:$(tag)'
        exitCode: '0'
    - task: Docker@2
      displayName: Docker Push
      inputs:
        containerRegistry: 'svc-acr'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'