trigger:
- main

variables:
  system.debug: true

pool:
  name: Projeto

stages:
- stage: Dev
  displayName: Dev
  jobs:
  - job: CI
    displayName: CI
    steps:
    - checkout: self
      fetchDepth: 0
    - task: SonarQubePrepare@7
      inputs:
        SonarQube: 'svc-sonar'
        scannerMode: 'cli'
        configMode: 'manual'
        cliProjectKey: 'myproject'
        cliProjectName: 'CI/CD'
        cliSources: '/home/azureuser/myagent/_work/1/s'
        extraProperties: |
          # Additional properties that will be passed to the scanner, 
          # Put one key=value per line, example:
          # sonar.exclusions=**/*.bin 
          sonar.java.binaries=.
          sonar.branch.name="" 
          sonar.scanner.metadataFilePath=""
          sonar.verbose=true
          sonar.log.level=DEBUG
    - task: SonarQubeAnalyze@7
      displayName: SonarAnalyze
      inputs:
        jdkversion: 'JAVA_HOME'
    
    - task: SonarQubePublish@7
      displayName: SonarGate
      inputs:
        pollingTimeoutSec: '300'
    
