trigger:
- main

variables:
  system.debug: true
  Build.SourceBranchName: 'master'
  
pool:
  name: Projeto

stages:
- stage: Dev
  displayName: Dev
  jobs:
  - job: CI
    displayName: CI
    steps:
    - checkout: self
      fetchDepth: 0
        
    - task: SonarQubePrepare@7
      inputs:
        SonarQube: 'svc-sonar'
        scannerMode: 'cli'
        configMode: 'manual'
        cliProjectKey: 'myproject-${Build.SourceBranchName}'
        cliProjectName: 'CI/CD'
        cliSources: '.'
        extraProperties: |
          # Additional properties that will be passed to the scanner, 
          # Put one key=value per line, example:
          # sonar.exclusions=**/*.bin
          sonar.log.level=DEBUG 
          sonar.verbose=true
          sonar.branch.name=""
          sonar.java.binaries=.
    - task: SonarQubeAnalyze@7
      displayName: SonarAnalyze
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'
    
    - task: SonarQubePublish@7
      displayName: SonarGate
      inputs:
        pollingTimeoutSec: '300'
    
